[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
; addopts = -v --html=reports/report.html
; addopts = -v --html=D:/orangehrm_selenium/reports/report.html
addopts= -v
markers =
    smoke: Smoke test cases
    regression: Regression test cases
    login: Login test cases